name: Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  auto-merge:
    if: github.actor == 'wingnut128' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash --repo ${{ github.repository }}
